In [ ]:
#numpy Assignment 1

In [40]:
# import numpy
import numpy as np

In [2]:
#Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#Create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
#Create an array of all the even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
#Create a 3x3 matrix with values ranging from 0 to 8
x=np.arange(0,9)
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.31238625])

#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.rand(25)

In [22]:
np.random.rand(25)

array([0.37689238, 0.75148427, 0.44341416, 0.90153015, 0.49411958,
       0.56683785, 0.67871759, 0.44117173, 0.72264484, 0.87670387,
       0.037349  , 0.25384678, 0.83937606, 0.80101949, 0.14177102,
       0.9353342 , 0.71194258, 0.94487978, 0.17461292, 0.02918442,
       0.26936956, 0.51662545, 0.9708492 , 0.16640634, 0.83896843])

In [23]:
np.random.rand(5,5)

array([[0.02622758, 0.95463873, 0.92896872, 0.07508809, 0.13485337],
       [0.55698119, 0.63709703, 0.64215421, 0.23169109, 0.73240867],
       [0.32421643, 0.55541605, 0.83825053, 0.58928672, 0.24860668],
       [0.45316346, 0.81025736, 0.14846204, 0.31578629, 0.91481881],
       [0.97514844, 0.9800726 , 0.74204882, 0.83611022, 0.95922435]])

In [33]:
#Create the following matrix:
x=np.arange(1,101)/100
x.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [34]:
#Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [39]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 1.95493482, -1.1228591 , -1.20860751,  0.67938657,  1.85752935,
        0.16257765, -1.76672064, -1.7503252 , -1.12194106,  0.012988  ,
        0.8689761 ,  0.8292431 ,  1.25178677, -0.6335392 ,  0.04824886,
        0.02691079, -0.76135778, -2.15578393, -0.53743855,  0.24518186,
       -0.97246318, -1.07876958, -0.8049709 , -0.36291241, -0.93702911])

In [6]:
# Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:
arr=np.arange(1,26)

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [22]:
arr1=arr.reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
arr1[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [25]:
arr1[3,4]

20

In [27]:
arr1[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [28]:
arr1[4, :]

array([21, 22, 23, 24, 25])

In [29]:
arr1[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
arr1.sum()

325

In [33]:
arr2=arr1[:,4:]

In [34]:
arr2

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [35]:
arr2.sum()

75

In [37]:
arr3=arr1[2]

In [38]:
arr3

array([11, 12, 13, 14, 15])

In [39]:
arr3.sum()

65